### ISSUE TITLE
sendSignedTransaction failing when calling getTransactionReceipt

### ISSUE THREAD

**Issue by erik-iglikov** [aionnetwork/aion_web3#62]
## Bug Report Template

Please include the following information when reporting an issue you are facing while using the Aion Web3 API.

**Web3 version**:  1.1.0

You can find this by executing:

`npm view aion-web3-v1.0 version`

**Command(s) triggering the issue**:
Deploy a contract using `sendSignedTransaction`.
Also sometimes fails on `getTransactionReceipt`.

What are the commands you're trying to send the API? This can be the JavaScript code you're running, or just the single command that seems like it's bugging. If possible, please include the parameters of the request as well.

**API output**: 

 Error: Failed to check for transaction receipt:
{}
    at Object._fireError (/home/erik/Downloads/8xdeploy/src/node_modules/aion-web3-utils/src/index.js:56:17)
    at /home/erik/Downloads/8xdeploy/src/node_modules/aion-web3-core-method/src/index.js:262:23

What does the API say in response? If the API errors out, please provide as much of the error message as possible.

P.S. this issue is inherited from Ethereum's web3 1.0 -> open issue on Ethereum's Web3 https://github.com/ethereum/web3.js/issues/1255

**Comment by erik-iglikov** [comment]
I found a solution https://github.com/ethereum/web3.js/pull/1735/commits/17dab677e9eaac8a98ddd436937835644ce8c6a4
