### ISSUE TITLE
format validation issue

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion_web3#7]
can be reproduced by running the txn-generator script from qa.

/home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/formatters.js:267
    throw new Error('invalid address');
    ^

Error: invalid address
    at inputAddressFormatter (/home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/formatters.js:267:11)
    at /home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/method.js:89:28
    at Array.map (<anonymous>)
    at Method.formatInput (/home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/method.js:88:32)
    at Method.toPayload (/home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/method.js:114:23)
    at Eth.send [as getCode] (/home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/method.js:139:30)
    at Object.callback (/home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/contract.js:122:39)
    at /home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/method.js:142:25
    at /home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/requestmanager.js:91:9
    at XMLHttpRequest.request.onreadystatechange (/home/nuco/alisharif/nuco/aion-qa/testbench/txn-generator/node_modules/aion-web3/lib/web3/httpprovider.js:120:13)

**Comment by ali-sharif** [comment]
debugged by @aion-anakha: has to do with use of isStrictAddress() to do address validation

**Comment by erik-iglikov** [comment]
@ali-sharif is this still an issue?

**Comment by ali-sharif** [comment]
This was an issue with the old web3 client version. No longer relevant for the 1.x.x release.
